@file:Suppress("RedundantVisibilityModifier")

package com.labijie.infra.snowflake.jdbc.pojo

import kotlin.Long
import kotlin.String

/**
 * POJO for SnowflakeSlotTable
 *
 * This code generated by an open-source project: Infra-Orm 
 * Project Site: https://github.com/hongque-pro/infra-orm.
 * Generator Version: unknown
 *
 *
 * Don't modify these codes !!
 *
 * Origin Exposed Table:
 * @see com.labijie.infra.snowflake.jdbc.SnowflakeSlotTable
 */
public open class SnowflakeSlot {
  public var instance: String = ""

  public var address: String = ""

  public var timeExpired: Long = 0L

  public var id: String = ""
}
