server:
  port: 8899

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dummy
    username: root
    password: test
  application:
    name: dummy
    
infra:
  exposed:
    generate-schema: true
  snowflake:
    provider: jdbc

