@file:Suppress("RedundantVisibilityModifier")

package com.labijie.infra.snowflake.jdbc.aot

import java.lang.ClassLoader
import org.springframework.aot.hint.MemberCategory
import org.springframework.aot.hint.RuntimeHints
import org.springframework.aot.hint.RuntimeHintsRegistrar
import org.springframework.aot.hint.TypeReference

/**
 * SpringBoot runtime hint for orm tables
 *
 * This code generated by an open-source project: Infra-Orm 
 * Project Site: https://github.com/hongque-pro/infra-orm.
 * Generator Version: 2.1.0
 *
 *
 * Don't modify these codes !!
 *
 * Origin Exposed Table:
 * @see com.labijie.infra.snowflake.jdbc.SnowflakeSlotTable
 */
internal class OrmPojoRuntimeHintsRegistrar : RuntimeHintsRegistrar {
  override fun registerHints(hints: RuntimeHints, classLoader: ClassLoader?) {
    // Begin Table Pojo types hint register
    hints.reflection().registerType(TypeReference.of("com.labijie.infra.snowflake.jdbc.pojo.SnowflakeSlot")) {
      it.withMembers(
      MemberCategory.PUBLIC_FIELDS,
      MemberCategory.INVOKE_DECLARED_CONSTRUCTORS,
      MemberCategory.INVOKE_PUBLIC_METHODS,
      )
    }
  }
}
