@file:Suppress("RedundantVisibilityModifier")

package com.labijie.infra.snowflake.jdbc.aot

import com.labijie.infra.orm.aot.registerOrmPojoType
import java.lang.ClassLoader
import org.springframework.aot.hint.RuntimeHints
import org.springframework.aot.hint.RuntimeHintsRegistrar

/**
 * SpringBoot runtime hint for orm tables
 *
 * This code generated by an open-source project: Infra-Orm 
 * Project Site: https://github.com/hongque-pro/infra-orm.
 * Generator Version: 2.1.0
 *
 *
 * Don't modify these codes !!
 *
 * Origin Exposed Table:
 * @see com.labijie.infra.snowflake.jdbc.SnowflakeSlotTable
 */
internal class OrmPojoRuntimeHintsRegistrar : RuntimeHintsRegistrar {
  override fun registerHints(hints: RuntimeHints, classLoader: ClassLoader?) {
    // Begin Table Pojo types hint register
    hints.registerOrmPojoType("com.labijie.infra.snowflake.jdbc.pojo.SnowflakeSlot")
  }
}
